Cardiac features
dado93/pywearable pull request #66
Opened 2024-01-08 16:36 UTC by Vaeliss

Update cardiac module to make it uniform to sleep module

2024-01-18 13:18 UTC, dado93 requested changes
@Vaeliss please check comments of the pull request

2024-01-18 13:18 UTC, dado93 commented on src/pywearable/activity.py
@Vaeliss do we need these changes in this pull request?

2024-01-18 13:18 UTC, dado93 commented on src/pywearable/loader/labfront/loader.py
@Vaeliss do we need to set "garmin_health_api" and not "health_api"? I think the main dictionary of the loader for common metrics uses "health_api"

2024-01-18 13:18 UTC, dado93 commented on src/pywearable/respiration.py
This will be updated in the respiratorion-features branch

2024-01-18 14:28 UTC, Vaeliss commented on setup.sh
Indeed not necessary, I need to remove it from the pull request completely

2024-01-23 16:44 UTC, Vaeliss commented on setup.sh
Deleted the file

2024-01-23 16:47 UTC, Vaeliss commented on src/pywearable/loader/labfront/loader.py
Main dictionary in the labfront loader module has key "garmin_health_api" for both HR and stress

2024-01-23 16:48 UTC, Vaeliss commented on src/pywearable/respiration.py
I deleted the addition of spo2, it will be expected from the respiration update directly

2024-01-23 16:50 UTC, Vaeliss commented on src/pywearable/activity.py
not really, but they're minor changes and will be included when the activity module is going to be updated to reflect the structure of the sleep module too.

2024-01-24 15:31 UTC, dado93 approved these changes

2024-01-24 15:32 UTC, merged